# Generated by Django 5.1.8 on 2025-12-05 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctorconsultation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Doctor Consultation', 'verbose_name_plural': 'Doctor Consultations'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationdispense',
            options={'ordering': ['-dispensed_date'], 'verbose_name': 'Medication Dispense', 'verbose_name_plural': 'Medication Dispenses'},
        ),
        migrations.AlterModelOptions(
            name='medicationstock',
            options={'ordering': ['expiry_date', 'batch_number'], 'verbose_name': 'Medication Stock', 'verbose_name_plural': 'Medication Stocks'},
        ),
        migrations.AlterModelOptions(
            name='patientbill',
            options={'ordering': ['-bill_date'], 'verbose_name': 'Patient Bill', 'verbose_name_plural': 'Patient Bills'},
        ),
        migrations.AlterModelOptions(
            name='patientregistration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Patient Registration', 'verbose_name_plural': 'Patient Registrations'},
        ),
        migrations.AlterModelOptions(
            name='pharmacybilling',
            options={'ordering': ['-bill_date', '-created_on'], 'verbose_name': 'Pharmacy Billing', 'verbose_name_plural': 'Pharmacy Billings'},
        ),
        migrations.AlterModelOptions(
            name='prescribedmedicine',
            options={'ordering': ['id'], 'verbose_name': 'Prescribed Medicine', 'verbose_name_plural': 'Prescribed Medicines'},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_id'], name='appointment_appoint_8c66d6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_1dd82b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__93c639_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_b8d203_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['visit_status'], name='appointment_visit_s_2d90a6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_active', 'appointment_date'], name='appointment_is_acti_a73da1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['visit_status', 'appointment_date'], name='appointment_visit_s_606565_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_active', 'appointment_date', 'visit_status'], name='appointment_is_acti_86e926_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorconsultation',
            index=models.Index(fields=['appointment'], name='doctor_cons_appoint_2e6ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorconsultation',
            index=models.Index(fields=['created_on'], name='doctor_cons_created_c282e5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorconsultation',
            index=models.Index(fields=['is_active'], name='doctor_cons_is_acti_a53a35_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='medication_name_418b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['is_active'], name='medication_is_acti_a78ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['dosage_form'], name='medication_dosage__9669f3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['prescribed_medicine'], name='medication__prescri_a82092_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['stock_entry'], name='medication__stock_e_8b0ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['dispensed_date'], name='medication__dispens_41e5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['dispensed_by'], name='medication__dispens_2a8843_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['is_active'], name='medication__is_acti_7eb035_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['medication', 'expiry_date'], name='medication__medicat_bd37fc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['batch_number'], name='medication__batch_n_e0b612_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['expiry_date'], name='medication__expiry__ae22c1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['is_active'], name='medication__is_acti_cc3b81_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['medication', 'is_active'], name='medication__medicat_7c12da_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['is_active', 'expiry_date'], name='medication__is_acti_ae29d0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['is_expired'], name='medication__is_expi_192b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['is_near_expiry'], name='medication__is_near_f39969_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['is_out_of_stock'], name='medication__is_out__ad7e91_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['bill_number'], name='patient_bil_bill_nu_f36ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['appointment'], name='patient_bil_appoint_c8c06a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['consultation'], name='patient_bil_consult_d26f47_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['bill_date'], name='patient_bil_bill_da_bd0894_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['payment_status'], name='patient_bil_payment_0c9a24_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['payment_status', 'bill_date'], name='patient_bil_payment_91224c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['is_active'], name='patient_bil_is_acti_31f03f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['created_on'], name='patient_bil_created_9e987c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(fields=['patient_id'], name='patient_reg_patient_c2e2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(fields=['contact_number'], name='patient_reg_contact_04b571_idx'),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(fields=['first_name', 'last_name'], name='patient_reg_first_n_b85c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(fields=['is_active'], name='patient_reg_is_acti_d1b93e_idx'),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(fields=['registration_date'], name='patient_reg_registr_37cbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['bill_number'], name='pharmacy_bi_bill_nu_97d433_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['bill_date'], name='pharmacy_bi_bill_da_a857e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['payment_status'], name='pharmacy_bi_payment_68690f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['payment_status', 'bill_date'], name='pharmacy_bi_payment_a2242c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['dispensed_by'], name='pharmacy_bi_dispens_b1e092_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['is_active'], name='pharmacy_bi_is_acti_ef9333_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybilling',
            index=models.Index(fields=['created_on'], name='pharmacy_bi_created_9d8691_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedicine',
            index=models.Index(fields=['consultation'], name='prescribed__consult_048594_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedicine',
            index=models.Index(fields=['medicine'], name='prescribed__medicin_58ff9a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedicine',
            index=models.Index(fields=['is_active'], name='prescribed__is_acti_249f98_idx'),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='doctorconsultation',
            table='doctor_consultation',
        ),
        migrations.AlterModelTable(
            name='medication',
            table='medication',
        ),
        migrations.AlterModelTable(
            name='medicationdispense',
            table='medication_dispense',
        ),
        migrations.AlterModelTable(
            name='medicationstock',
            table='medication_stock',
        ),
        migrations.AlterModelTable(
            name='patientbill',
            table='patient_bill',
        ),
        migrations.AlterModelTable(
            name='patientregistration',
            table='patient_registration',
        ),
        migrations.AlterModelTable(
            name='pharmacybilling',
            table='pharmacy_billing',
        ),
        migrations.AlterModelTable(
            name='prescribedmedicine',
            table='prescribed_medicine',
        ),
    ]
