# Generated by Django 5.1.8 on 2025-12-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(help_text='Auto-generated unique order number (e.g., LAB-2025-0001)', max_length=50, unique=True)),
                ('selected_tests', models.JSONField(default=list, help_text='Array of selected test details: [{id, name, category, price}, ...]')),
                ('external_lab_name', models.CharField(blank=True, help_text="Name of external laboratory (e.g., 'Path Lab', 'Dr. Lal PathLabs')", max_length=200, null=True)),
                ('external_reference_number', models.CharField(blank=True, help_text='Reference number provided by external lab', max_length=100, null=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SENT', 'Sent to External Lab'), ('RECEIVED', 'Results Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', help_text='Current status of the lab order', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill amount before discount', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far (sum of all transactions)', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid (total - paid - discount)', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount applied', max_digits=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', help_text='Payment status (supports partial payments)', max_length=20)),
                ('date_ordered', models.DateField(auto_now_add=True, help_text='Date when order was created')),
                ('date_sent', models.DateField(blank=True, help_text='Date when samples were sent to external lab', null=True)),
                ('date_received', models.DateField(blank=True, help_text='Date when results were received from external lab', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions or notes for the lab')),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment (null for walk-in patients)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='data_hub.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for whom tests are ordered', on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='data_hub.patientregistration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updatedby_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Test Order',
                'verbose_name_plural': 'Lab Test Orders',
                'ordering': ['-date_ordered', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LabPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(help_text='Auto-generated unique transaction ID', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('NETBANKING', 'Net Banking'), ('CREDIT', 'Credit')], help_text='Payment method (CASH/CARD/UPI/etc.)', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of payment')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number (if generated)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(help_text='Staff member who received the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_payments_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updatedby_set', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(help_text='Related lab test order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='data_hub.labtestorder')),
            ],
            options={
                'verbose_name': 'Lab Payment Transaction',
                'verbose_name_plural': 'Lab Payment Transactions',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_pdf', models.FileField(help_text='PDF report file (organized by year/month)', upload_to='lab_reports/%Y/%m/')),
                ('report_date', models.DateField(help_text='Date mentioned on the lab report')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, help_text='Date and time of upload')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations about the report')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(help_text='Related lab test order', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data_hub.labtestorder')),
                ('patient', models.ForeignKey(help_text='Patient (denormalized for quick queries)', on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='data_hub.patientregistration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updatedby_set', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Test Result',
                'verbose_name_plural': 'Lab Test Results',
                'ordering': ['-report_date', '-uploaded_on'],
            },
        ),
        migrations.AddIndex(
            model_name='labtestorder',
            index=models.Index(fields=['order_number'], name='data_hub_la_order_n_72370a_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestorder',
            index=models.Index(fields=['patient', 'date_ordered'], name='data_hub_la_patient_3f49f1_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestorder',
            index=models.Index(fields=['status', 'payment_status'], name='data_hub_la_status_e81939_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestorder',
            index=models.Index(fields=['date_ordered'], name='data_hub_la_date_or_42852c_idx'),
        ),
        migrations.AddIndex(
            model_name='labpaymenttransaction',
            index=models.Index(fields=['transaction_id'], name='data_hub_la_transac_6e3658_idx'),
        ),
        migrations.AddIndex(
            model_name='labpaymenttransaction',
            index=models.Index(fields=['lab_order', 'payment_date'], name='data_hub_la_lab_ord_183215_idx'),
        ),
        migrations.AddIndex(
            model_name='labpaymenttransaction',
            index=models.Index(fields=['payment_date'], name='data_hub_la_payment_50d4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestresult',
            index=models.Index(fields=['patient', 'report_date'], name='data_hub_la_patient_3c9d85_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestresult',
            index=models.Index(fields=['lab_order'], name='data_hub_la_lab_ord_5d029f_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestresult',
            index=models.Index(fields=['uploaded_on'], name='data_hub_la_uploade_02aae7_idx'),
        ),
    ]
