# Generated by Django 5.1.8 on 2025-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_labtestorder_labpaymenttransaction_labtestresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='lab_departments',
            field=models.ManyToManyField(help_text='Lab departments/test categories ordered (e.g., Hematology, Biochemistry)', related_name='lab_orders', to='data_hub.labdepartment'),
        ),
        migrations.AlterField(
            model_name='labtestorder',
            name='selected_tests',
            field=models.JSONField(default=list, help_text='Array of selected test details for quick display: [{id, name, category, price}, ...]'),
        ),
    ]
