# Generated by Django 5.1.8 on 2025-12-15 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0004_labtestorder_lab_departments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this stock has been verified/approved by pharmacist. Unverified stock cannot be dispensed.'),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacist who verified this stock entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='When this stock was verified', null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacist who approved this GRN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='When GRN was approved', null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='GRN approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='stock_created',
            field=models.BooleanField(default=False, help_text='Whether stock entries have been created (happens on approval)'),
        ),
    ]
