# Generated by Django 5.1.8 on 2025-12-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0005_medicationstock_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicinereturn',
            name='pharmacy_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_returns', to='data_hub.pharmacybilling'),
        ),
        migrations.AlterField(
            model_name='patientmedicinereturn',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_returns', to='data_hub.patientregistration'),
        ),
        migrations.AlterField(
            model_name='patientmedicinereturn',
            name='patient_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_returns', to='data_hub.patientbill'),
        ),
        migrations.AddConstraint(
            model_name='patientmedicinereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient_bill__isnull', False), ('pharmacy_bill__isnull', True)), models.Q(('patient_bill__isnull', True), ('pharmacy_bill__isnull', False)), _connector='OR'), name='either_patient_bill_or_pharmacy_bill'),
        ),
    ]
