# Generated by Django 5.1.8 on 2025-12-23 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0006_patientmedicinereturn_pharmacy_bill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='casualty_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity allocated to casualty/emergency'),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='home_care_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity allocated to home care'),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='pharmacy_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity allocated to main pharmacy'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_department', models.CharField(choices=[('PHARMACY', 'Main Pharmacy'), ('HOME_CARE', 'Home Care'), ('CASUALTY', 'Casualty/Emergency')], help_text='Source department', max_length=20)),
                ('to_department', models.CharField(choices=[('PHARMACY', 'Main Pharmacy'), ('HOME_CARE', 'Home Care'), ('CASUALTY', 'Casualty/Emergency')], help_text='Destination department', max_length=20)),
                ('quantity_transferred', models.PositiveIntegerField(help_text='Number of units transferred')),
                ('reason', models.TextField(help_text="Reason for transfer (e.g., 'Home care stock low')")),
                ('transfer_date', models.DateTimeField(auto_now_add=True, help_text='When transfer was created')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', help_text='Transfer status', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('stock_entry', models.ForeignKey(help_text='Stock batch being transferred', on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='data_hub.medicationstock')),
                ('transferred_by', models.ForeignKey(help_text='User who authorized the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updatedby_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'stock_transfer',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['stock_entry'], name='stock_trans_stock_e_8d6ac7_idx'), models.Index(fields=['from_department'], name='stock_trans_from_de_569dfd_idx'), models.Index(fields=['to_department'], name='stock_trans_to_depa_4c5c16_idx'), models.Index(fields=['transfer_date'], name='stock_trans_transfe_5c734b_idx'), models.Index(fields=['status'], name='stock_trans_status_dddd0a_idx'), models.Index(fields=['transferred_by'], name='stock_trans_transfe_ecaeb5_idx')],
            },
        ),
    ]
