# Generated by Django 5.1.8 on 2025-12-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0007_add_stock_allocation_and_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of packs/strips received (e.g., 50 strips)', null=True),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='price_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per pack/strip (e.g., ₹180 per strip)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Calculated: price_per_pack ÷ units_per_pack', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated: pack_quantity × units_per_pack (total tablets/units)', null=True),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='units_per_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units per pack (e.g., 15 tablets per strip)', null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of packs/strips received (e.g., 50 strips)', null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='price_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per pack/strip (e.g., ₹180 per strip)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Calculated: price_per_pack ÷ units_per_pack', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated: pack_quantity × units_per_pack (total tablets/units)', null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units per pack (e.g., 15 tablets per strip)', null=True),
        ),
        migrations.AlterField(
            model_name='medicationstock',
            name='packing',
            field=models.CharField(blank=True, help_text='Legacy packing details - Auto-generated from structured fields', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='packing',
            field=models.CharField(blank=True, help_text='Legacy packing details - Auto-generated from structured fields', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity purchased (will be auto-calculated from pack_quantity × units_per_pack)'),
        ),
    ]
